-- =====================================================
-- 002_create_users_table.sql
-- 사용자 테이블 생성
-- 
-- 실행 방법:
--   psql "postgresql://postgres.xyqpggpilgcdsawuvpzn:ZNDqDunnaydr0aFQ@aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres" -f docs/sql/002_create_users_table.sql
-- =====================================================

-- 1. 사용자 테이블 생성
CREATE TABLE IF NOT EXISTS mmcheck.tbl_users (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    auth_id uuid NOT NULL UNIQUE,
    email text NOT NULL UNIQUE,
    username text UNIQUE,
    display_name text,
    avatar_url text,
    bio text,
    points integer DEFAULT 0,
    level text DEFAULT 'bronze' CHECK (level = ANY (ARRAY['bronze'::text, 'silver'::text, 'gold'::text, 'platinum'::text, 'diamond'::text])),
    subscribed_projects_count integer DEFAULT 0,
    supported_projects_count integer DEFAULT 0,
    projects_count integer DEFAULT 0,
    is_active boolean DEFAULT true,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    links jsonb DEFAULT '{}'::jsonb,
    user_type text DEFAULT 'user' NOT NULL CHECK (user_type = ANY (ARRAY['user'::text, 'bot'::text])),
    oauth_avatar_url text
);

-- 2. 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_tbl_users_auth_id ON mmcheck.tbl_users(auth_id);
CREATE INDEX IF NOT EXISTS idx_tbl_users_email ON mmcheck.tbl_users(email);
CREATE INDEX IF NOT EXISTS idx_tbl_users_username ON mmcheck.tbl_users(username);
CREATE INDEX IF NOT EXISTS idx_tbl_users_links ON mmcheck.tbl_users USING gin(links);
CREATE INDEX IF NOT EXISTS idx_tbl_users_oauth_avatar_url ON mmcheck.tbl_users(oauth_avatar_url) WHERE oauth_avatar_url IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_tbl_users_user_type ON mmcheck.tbl_users(user_type) WHERE user_type = 'bot'::text;

-- 3. RLS (Row Level Security) 설정
ALTER TABLE mmcheck.tbl_users ENABLE ROW LEVEL SECURITY;

-- 기존 정책이 있다면 삭제
DROP POLICY IF EXISTS "users_select_policy" ON mmcheck.tbl_users;
DROP POLICY IF EXISTS "users_self_select_policy" ON mmcheck.tbl_users;
DROP POLICY IF EXISTS "users_insert_policy" ON mmcheck.tbl_users;
DROP POLICY IF EXISTS "users_update_policy" ON mmcheck.tbl_users;

-- [SELECT] 인증된 모든 사용자가 다른 사용자의 프로필을 조회할 수 있도록 허용
CREATE POLICY "users_select_policy" ON mmcheck.tbl_users
    FOR SELECT TO authenticated USING (true);

-- [SELECT] 자신의 데이터는 무조건 접근 가능하도록 강화 (백업용)
CREATE POLICY "users_self_select_policy" ON mmcheck.tbl_users
    FOR SELECT TO authenticated USING (auth_id = auth.uid());

-- [INSERT] 신규 사용자는 자신의 auth_id로만 레코드 생성 가능
CREATE POLICY "users_insert_policy" ON mmcheck.tbl_users
    FOR INSERT TO authenticated WITH CHECK (auth_id = auth.uid());

-- [UPDATE] 사용자는 자신의 정보만 수정 가능
CREATE POLICY "users_update_policy" ON mmcheck.tbl_users
    FOR UPDATE TO authenticated USING (auth_id = auth.uid());

-- 4. 권한 부여
GRANT SELECT ON mmcheck.tbl_users TO anon;
GRANT SELECT, INSERT, UPDATE ON mmcheck.tbl_users TO authenticated;

-- 5. 코멘트 추가
COMMENT ON TABLE mmcheck.tbl_users IS '사용자 정보를 저장하는 테이블';
COMMENT ON COLUMN mmcheck.tbl_users.id IS '사용자 고유 ID (PK)';
COMMENT ON COLUMN mmcheck.tbl_users.auth_id IS 'Supabase Auth의 user.id';
COMMENT ON COLUMN mmcheck.tbl_users.email IS '사용자 이메일';
COMMENT ON COLUMN mmcheck.tbl_users.username IS '사용자 아이디 (URL 등에서 사용)';
COMMENT ON COLUMN mmcheck.tbl_users.display_name IS '사용자 표시 이름';
COMMENT ON COLUMN mmcheck.tbl_users.avatar_url IS '사용자 프로필 이미지 경로';
COMMENT ON COLUMN mmcheck.tbl_users.bio IS '자기소개';
COMMENT ON COLUMN mmcheck.tbl_users.points IS '활동 포인트';
COMMENT ON COLUMN mmcheck.tbl_users.level IS '등급 (bronze, silver, gold, platinum, diamond)';
COMMENT ON COLUMN mmcheck.tbl_users.links IS '소셜 링크 정보 (JSON)';
COMMENT ON COLUMN mmcheck.tbl_users.user_type IS '사용자 타입 (user, bot)';
